# Generated by Django 5.2.13 on 2026-09-02 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_faceprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverprofile',
            old_name='status',
            new_name='approval_status',
        ),
        migrations.RenameField(
            model_name='faceprofile',
            old_name='status',
            new_name='approval_status',
        ),
        migrations.AddField(
            model_name='driverlicense',
            name='back_image_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='driverlicense',
            name='front_image_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='faceprofile',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='driver_license', to='accounts.driverprofile'),
        ),
        migrations.AlterField(
            model_name='faceprofile',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='face_profile', to='accounts.driverprofile'),
        ),
    ]
