# Generated by Django 5.2.17 on 2026-09-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_driverprofile_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
