# Generated by Django 5.2.13 on 2026-09-25 02:47

from django.db import migrations, models
from django.utils import timezone


def reconcile_profiles(apps, schema_editor):
    Driver = apps.get_model('accounts', 'DriverProfile')
    License = apps.get_model('accounts', 'DriverLicense')
    Face = apps.get_model('accounts', 'FaceProfile')
    alias = schema_editor.connection.alias
    for driver in Driver.objects.using(alias).iterator():
        license = License.objects.using(alias).filter(driver_id=driver.pk).first()
        face = Face.objects.using(alias).filter(driver_id=driver.pk).first()
        complete = all((driver.full_name.strip(), driver.date_of_birth, driver.phone.strip(), driver.address.strip(),
                        license and license.license_number and license.license_class and license.front_image_url and license.back_image_url,
                        face and face.face_image_url and face.embedding))
        status = driver.approval_status
        if not complete:
            status = 'INCOMPLETE'
        elif status == 'APPROVED':
            # Previous approval only covered personal details; require an overall review.
            status = 'PENDING'
        Driver.objects.using(alias).filter(pk=driver.pk).update(approval_status=status, updated_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_driverprofile_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='approval_status',
            field=models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='INCOMPLETE', max_length=10),
        ),
        migrations.RunPython(reconcile_profiles, migrations.RunPython.noop),
    ]
