# Generated by Django 5.2.17 on 2026-09-02 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_drivervehicleassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='vehicletype',
            name='code',
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='Unnamed Device', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='category',
            field=models.CharField(choices=[('TRUCK', 'Truck'), ('BUS', 'Bus')], default='TRUCK', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], default='OFFLINE', max_length=15),
        ),
    ]
