# Generated by Django 5.2.17 on 2026-09-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_remove_device_device_type_remove_vehicletype_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], default='ACTIVE', max_length=10),
        ),
    ]
