# Generated by Django 5.2.17 on 2026-09-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_vehicletype_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('INACTIVE', 'Ngừng hoạt động'), ('LIQUIDATED', 'Đã thanh lý')], default='ACTIVE', max_length=10),
        ),
    ]
