# Generated by Django 5.2.17 on 2026-09-24 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_vehicletype_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicletype',
            name='status',
        ),
    ]
