# Generated by Django 5.2.13 on 2026-10-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_remove_vehicletype_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='api_key_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=128),
        ),
    ]
