# Generated by Django 5.2.17 on 2026-09-23 11:06

import django.db.models.deletion
from django.db import migrations, models


def backfill_vehicle(apps, schema_editor):
    Session = apps.get_model('driving', 'DrivingSession')
    alias = schema_editor.connection.alias
    rows = Session.objects.using(alias).select_related('assignment').all()
    active_vehicles = set()
    for row in rows.iterator():
        valid = ((row.status == 'STARTED' and row.ended_at is None)
                 or (row.status == 'ENDED' and row.ended_at is not None and row.ended_at >= row.started_at))
        if not valid:
            raise RuntimeError(f'Invalid session {row.pk}: fix status/times before migrating.')
        vehicle_id = row.assignment.vehicle_id
        if row.status == 'STARTED':
            if vehicle_id in active_vehicles:
                raise RuntimeError(f'Multiple active sessions for vehicle {vehicle_id}; review before migrating.')
            active_vehicles.add(vehicle_id)
        Session.objects.using(alias).filter(pk=row.pk).update(vehicle_id=vehicle_id)


class Migration(migrations.Migration):

    dependencies = [
        ('driving', '0001_initial'),
        ('vehicles', '0005_remove_device_device_type_remove_vehicletype_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingsession',
            name='vehicle',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driving_sessions', to='vehicles.vehicle'),
        ),
        migrations.RunPython(backfill_vehicle, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='drivingsession', name='vehicle',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='driving_sessions', to='vehicles.vehicle'),
        ),
        migrations.AddConstraint(
            model_name='drivingsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', True), ('status', 'STARTED')), models.Q(('ended_at__gte', models.F('started_at')), ('ended_at__isnull', False), ('status', 'ENDED')), _connector='OR'), name='session_consistent_times_status'),
        ),
        migrations.AddConstraint(
            model_name='drivingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'STARTED')), fields=('vehicle',), name='one_started_session_per_vehicle'),
        ),
    ]
