# Generated by Django 5.2.17 on 2026-09-23 09:33

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driving', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Mã chỉ gồm chữ in hoa, số và dấu gạch dưới.')])),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'pk'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='violation_type_code_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('LOW', 'Thấp'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao')], max_length=10)),
                ('detected_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('APPROVED', 'Đã xác nhận'), ('REJECTED', 'Đã từ chối'), ('REVOKED', 'Đã thu hồi')], default='PENDING', max_length=10)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='driving.drivingsession')),
                ('violation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='violations.violationtype')),
            ],
            options={
                'ordering': ['-detected_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IMAGE', 'Ảnh'), ('VIDEO', 'Video')], max_length=5)),
                ('url', models.URLField(max_length=2000, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('cloudinary_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('captured_at', models.DateTimeField()),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='violations.violation')),
            ],
            options={
                'ordering': ['captured_at', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', ['IMAGE', 'VIDEO'])), name='evidence_valid_type')],
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('APPROVED', 'Đã chấp nhận'), ('REJECTED', 'Đã từ chối')], default='PENDING', max_length=10)),
                ('admin_response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('violation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='violations.violation')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED', 'REJECTED'])), name='appeal_valid_status')],
            },
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['status', '-detected_at'], name='violation_status_detected_idx'),
        ),
        migrations.AddConstraint(
            model_name='violation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED', 'REJECTED', 'REVOKED'])), name='violation_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='violation',
            constraint=models.CheckConstraint(condition=models.Q(('severity__in', ['LOW', 'MEDIUM', 'HIGH'])), name='violation_valid_severity'),
        ),
    ]
